### ISSUE TITLE
Hard to know what error is being raised when doing a New

### ISSUE THREAD

**Issue by cedmundo** [jimmy-go/recaptcha#1]
I'm trying to check what error is returning the function `recaptcha.New` as follows: 

```
re, err := recaptcha.New(myID, myKey)
if err == ??? {

} else if err == ??? {

} else if err != nil {

}
```

Currently I'm trying to use `err == errors.New("recaptcha: invalid key length")` but I don't know if its the correct way of doing this.

**Comment by jimmy-go** [comment]
Well... very rarely you have to do that in a New function return because you need to check for an error only. But anyway the errors are exported now.
